import axios from 'axios';
import Head from 'next/head'
import { useEffect, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCheck, faTimes, faAdjust } from '@fortawesome/free-solid-svg-icons'

export default function Home() {

  const [number, setNumber] = useState("918225808241")
  const [res, setRes] = useState({});
  const[dark, setDark] = useState(false);

  const handleSearch = (e) => {
    e.preventDefault();

    setNumber(e.target[0].value);
  }

  useEffect(() => {
    axios.get(`http://apilayer.net/api/validate?access_key=e52d69f119348057d68ec090d2d10978&number=${number}`).then(response => {
      const data = response.data;
      setRes(data);
    })
  }, [number])

  return (
    <div className={dark ? "dark" : ""}>
      <Head>
        <title>Numverify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen dark:bg-gray-800 bg-gray-50 relative">
        <div className="h-16 dark:bg-gray-800 bg-gray-50 shadow-md dark:shadow-dark flex justify-center items-center mb-5">
          {/* <div></div> */}
          <span className="text-gradient font-bold text-xl">NumVerify</span>
          <button className={`absolute right-10 p-3 shadow-md rounded-full ${dark ? "bg-white" : "bg-gray-900"}`} onClick={() => {setDark(!dark)}}>
            <FontAwesomeIcon className={`w-4 ${dark ? "text-gray-800" : "text-white"}`} icon={faAdjust} />
          </button>
        </div>

        <div className="container">
          <div className="flex justify-center">
            <form className="flex justify-between w-full lg:w-4/5 xl:w-2/3" onSubmit={handleSearch}>
              <input className="bg-white dark:bg-gray-900 dark:text-white dark:border-gray-900 border-white border-2 hover:border-red-500 rounded-lg h-10 w-full mr-2 shadow-md hover:shadow-lg pl-5" placeholder="Enter mobile number with country code"/>
              <button type="submit" className="btn bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500 rounded-lg h-10 px-10 text-white dark:text-black font-semibold shadow-md hover:shadow-lg">Search</button>
            </form>
          </div>
          <div className="flex justify-center mt-10">
            <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md hover:shadow-lg p-4 w-full lg:w-4/5 xl:w-2/3">
              <div className="flex border-b-2 p-2 dark:border-gray-700">
                <div className="w-1/2 font-semibold dark:text-white">Number:</div>
                <div className="w-1/2 dark:text-white">{res.number}</div>
              </div>
              <div className="flex border-b-2 p-2 dark:border-gray-700">
                <div className="w-1/2 dark:text-white font-semibold">Carrier:</div>
                <div className="w-1/2 dark:text-white md:whitespace-nowrap">{res.carrier}</div>
              </div>
              <div className="flex border-b-2 p-2 dark:border-gray-700">
                <div className="w-1/2 dark:text-white font-semibold">Local Format:</div>
                <div className="w-1/2 dark:text-white">{res.local_format}</div>
              </div>
              <div className="flex border-b-2 p-2 dark:border-gray-700">
                <div className="w-1/2 dark:text-white font-semibold">International:</div>
                <div className="w-1/2 dark:text-white">{res.international_format}</div>
              </div>
              <div className="flex border-b-2 p-2 dark:border-gray-700">
                <div className="w-1/2 dark:text-white font-semibold">Country Prefix:</div>
                <div className="w-1/2 dark:text-white">{res.country_prefix}</div>
              </div>
              <div className="flex border-b-2 p-2 dark:border-gray-700">
                <div className="w-1/2 dark:text-white font-semibold">Line Type:</div>
                <div className="w-1/2 dark:text-white capitalize">{res.line_type}</div>
              </div>
              <div className="flex border-b-2 p-2 dark:border-gray-700">
                <div className="w-1/2 dark:text-white font-semibold">Country:</div>
                <div className="w-1/2 dark:text-white">{res.country_name}</div>
              </div>
              <div className="flex border-b-2 p-2 dark:border-gray-700">
                <div className="w-1/2 dark:text-white font-semibold">Location:</div>
                <div className="w-1/2 dark:text-white">{res.location}</div>
              </div>
              <div className="flex p-2">
                <div className="w-1/2 dark:text-white font-semibold">Valid:</div>
                <div className="w-1/2 dark:text-white">
                  {
                    res.valid ?
                    <FontAwesomeIcon className="w-4 text-green-500" icon={faCheck} />
                    :
                    <FontAwesomeIcon className="w-4 text-red-500" icon={faTimes} />
                  }
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
